Repository mini0212/Even_Youtube, pull requests merged in 2024-12, with the labels that each got.

#18 검색 헤더 미디어쿼리 적용 및 UI 수정
  index.html
  index.js
  styles/header.css
Labels: 🎨 UI

#21 Feature/sidebar 추가
  .vscode/settings.json
  README.md
  assets/icons/1. Home.png
  assets/icons/10. Shopping.png
  assets/icons/11. Music.png
  assets/icons/12. Movies.png
  assets/icons/13. Live.png
  assets/icons/14. Gaming.png
  assets/icons/15. News.png
  assets/icons/16. Educate.png
  assets/icons/17. Podcasts.png
  assets/icons/18. Youtube_Premium.png
  assets/icons/19. YouTube_Studio.png
  assets/icons/2. Shorts.png
  assets/icons/20. Youtube_Music.png
  assets/icons/21.Youtube_Kids.png
  assets/icons/22. Setting.png
  assets/icons/23. Report_history.png
  assets/icons/24. Help.png
  assets/icons/25. Support.png
  assets/icons/3. Subscribe.png
  assets/icons/4. Watching.png
  assets/icons/5. Playlist.png
  assets/icons/6. My_video.png
  assets/icons/7. Watch_later.png
  assets/icons/8. Liker_video.png
  assets/icons/9. Trending.png
  assets/icons/logo.png
  index.html
  styles/general.css
  styles/sidebar.css
Labels: 🎨 UI

#22 Video grid 추가
  index.html
  script.js
  styles/main.css
Labels: 🎨 UI

#23 Feature/header
  .vscode/settings.json
  assets/icons/add-video.png
  assets/icons/back.png
  assets/icons/edit.png
  assets/icons/keyboard.png
  assets/icons/live.png
  assets/icons/logo-dark.png
  assets/icons/menu.png
  assets/icons/next.png
  assets/icons/notification.png
  assets/icons/profile.png
  assets/icons/search.png
  assets/icons/setting.png
  assets/icons/video-clip.png
  assets/icons/voice.png
  index.html
  index.js
  styles/header.css
Labels: 🎨 UI

#24 스타일 대대적인 수정 1차
  index.html
  styles/header.css
  styles/main.css
  styles/sidebar.css
Labels: 🎨 UI

#25 헤더 right section 쏠림 수정
  styles/header.css
Labels: 🐛 bug

#26 nav 부분 수정
  assets/icons/back-btn-icon.png
  assets/icons/next-btn-icon.png
  index.html
  index.js
  styles/main.css
Labels: 🎨 UI

#27 전체 색상 변경, nav-scroll-btn active효과 추가, 사이드바 위치 조정 및 사이드 바 헤더 추가, 컨텐츠 푸터 삭제
  index.html
  styles/header.css
  styles/main.css
  styles/sidebar.css
Labels: 🎨 UI

#28 헤더 배경 색상 수정
  styles/header.css
Labels: 🐛 bug

#31 사이드바 확장 시 오버레이 추가, 스크롤 방지 추가
  hamburger.js
  index.html
  styles/main.css
Labels: 🎨 UI

#32 검색 기능 추가, 검색 버튼 추가
  index.html
  index.js
  script.js
  styles/header.css
  styles/video.css
Labels: 🌟 feat, 🎨 UI

#33 검색 탭 버그 수정
  index.html
  index.js
  script.js
  styles/header.css
Labels: 🐛 bug

#34 Release 1.0.0
  .vscode/settings.json
  README.md
  assets/icons/1. Home.png
  assets/icons/10. Shopping.png
  assets/icons/11. Music.png
  assets/icons/12. Movies.png
  assets/icons/13. Live.png
  assets/icons/14. Gaming.png
  assets/icons/15. News.png
  assets/icons/16. Educate.png
  assets/icons/17. Podcasts.png
  assets/icons/18. Youtube_Premium.png
  assets/icons/19. YouTube_Studio.png
  assets/icons/2. Shorts.png
  assets/icons/20. Youtube_Music.png
  assets/icons/21.Youtube_Kids.png
  assets/icons/22. Setting.png
  assets/icons/23. Report_history.png
  assets/icons/24. Help.png
  assets/icons/25. Support.png
  assets/icons/3. Subscribe.png
  assets/icons/4. Watching.png
  assets/icons/5. Playlist.png
  assets/icons/6. My_video.png
  assets/icons/7. Watch_later.png
  assets/icons/8. Liker_video.png
  assets/icons/9. Trending.png
  assets/icons/add-video.png
  assets/icons/back-btn-icon.png
  assets/icons/back.png
  assets/icons/edit.png
  assets/icons/keyboard.png
  assets/icons/live.png
  assets/icons/logo-dark.png
  assets/icons/logo.png
  assets/icons/menu.png
  assets/icons/next-btn-icon.png
  assets/icons/next.png
  assets/icons/notification.png
  assets/icons/profile.png
  assets/icons/search.png
  assets/icons/setting.png
  assets/icons/video-clip.png
  assets/icons/voice.png
  hamburger.js
  index.html
  index.js
  script.js
  styles/general.css
  styles/header.css
  styles/main.css
  styles/sidebar.css
  styles/video.css
Labels: 🌟 feat

#35 경로 수정
  index.html
  js/hamburger.js
  js/index.js
  js/script.js
  styles/sidebar.css
Labels: 🐛 bug

#37 Sync Develop
  assets/icons/Educate.png
  assets/icons/Gaming.png
  assets/icons/Help.png
  assets/icons/Home.png
  assets/icons/Liker_video.png
  assets/icons/Movies.png
  assets/icons/Music.png
  assets/icons/My_video.png
  assets/icons/News.png
  assets/icons/Playlist.png
  assets/icons/Podcasts.png
  assets/icons/Report_history.png
  assets/icons/Shopping.png
  assets/icons/Shorts.png
  assets/icons/Subscribe.png
  assets/icons/Support.png
  assets/icons/Trending.png
  assets/icons/Watch_later.png
  assets/icons/Watching.png
  assets/icons/YouTube_Studio.png
  assets/icons/Youtube_Kids.png
  assets/icons/Youtube_Music.png
  assets/icons/Youtube_Premium.png
  assets/icons/yt_Live.png
  assets/icons/yt_Setting.png
  index.html
  styles/sidebar.css
Labels: 🔄 sync

#39 Sync Develop
  index.html
Labels: 🔄 sync
